include $(TOPDIR)/rules.mk

PKG_NAME:=tgwireguard
PKG_VERSION:=2.0.9
PKG_RELEASE:=1

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://github.com/torguardvpn/tgwireguard.git
PKG_SOURCE_VERSION:=bf52d042cae8ad7b2622671918c0e77693cf6ff5
PKG_MIRROR_HASH:=e6149208db0635fe884300e5d3cd42277192f98222451aef3bca43ead0fb9eb4

include $(INCLUDE_DIR)/package.mk

define Package/tgwireguard
  SECTION:=luci
  CATEGORY:=LuCI
  SUBMENU:=7. TorGuard
  TITLE:=LuCI config tools for TorGuard WireGuard client
  DEPENDS:=+kmod-wireguard +wireguard-tools +luci-lua-runtime
  PKGARCH:=all
endef

define Package/tgwireguard/description
  LuCI configuration for WireGuard VPN, provided by TorGuard.
endef

define Package/tgwireguard/conffiles
/etc/config/tgwireguard_cfg
endef

define Build/Compile
endef

define Package/tgwireguard/install
	$(INSTALL_DIR) $(1)/etc/config
	$(INSTALL_DIR) $(1)/etc/init.d
	$(INSTALL_DIR) $(1)/etc/uci-defaults
	$(INSTALL_DIR) $(1)/usr/lib/lua/luci/controller/admin
	$(INSTALL_DIR) $(1)/usr/lib/lua/luci/model/cbi/torguard

	$(INSTALL_CONF) $(PKG_BUILD_DIR)/files/etc/config/tgwireguard_cfg $(1)/etc/config/
	$(INSTALL_BIN)  $(PKG_BUILD_DIR)/files/etc/init.d/tgwireguard $(1)/etc/init.d/
	$(INSTALL_BIN)  $(PKG_BUILD_DIR)/files/etc/uci-defaults/tgwireguard_def $(1)/etc/uci-defaults/
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/files/usr/lib/lua/luci/controller/admin/tgwireguard.lua $(1)/usr/lib/lua/luci/controller/admin/
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/files/usr/lib/lua/luci/model/cbi/torguard/tgwireguard.lua $(1)/usr/lib/lua/luci/model/cbi/torguard/
endef

$(eval $(call BuildPackage,$(PKG_NAME)))
